# https://github.com/openai/codex/blob/main/docs/config.md

profile = "codex"

model_reasoning_effort = "high"
model_reasoning_summary = "detailed"

approval_policy = "on-request"
sandbox_mode = "workspace-write"

show_raw_agent_reasoning = true

[tui]
notifications = true

[features]
web_search_request = true

[profiles.my-gpt-5]
model = "gpt-5.1-chat"
model_provider = "azure-chat"

[profiles.codex]
model = "openai/gpt-5.1-codex"
model_provider = "litellm"

[model_providers.azure-chat]
name = "azure-chat"
wire_api = "chat"
base_url = "https://safuapi.prod.secfdg.net/openai/deployments/gpt-5.1-chat"
query_params = { api-version = "2025-04-01-preview" }
env_key = "OPENAI_API_KEY"

[model_providers.litellm]
name = "litellm"
wire_api = "chat"
base_url = "https://litellm.safuapi.prod.secfdg.net"
env_key = "OPENAI_API_KEY"
