"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [1, 3, 4]
show_hidden = true
show_symlink = true
sort_by = "extension"
linemode = "size_and_mtime"

[preview]
wrap = "yes"
#max_width = 2000
#max_height = 2000

[tasks]
suppress_preload = true

[open]
append_rules = [{ url = "*", use = ["open", "edit", "reveal"] }]
