[general]
import = ["dracula.toml"]
working_directory = "/Users/leo/Downloads"

[terminal.shell]
program = "/Users/leo/.pixi/bin/fish"

[env]
TERM = "xterm-256color"

[bell]
animation = "EaseOutSine"
color = "#4e4e4e"
duration = 600

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[font]
size = 14

[font.normal]
family = "Maple Mono Normal NF CN"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
dynamic_title = true
dynamic_padding = true
opacity = 0.88
startup_mode = "Maximized"
option_as_alt = "Both"
decorations_theme_variant = "Dark"
